### ISSUE TITLE
Please convert the projects to be imported via Android-Studio

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [vogellacompany/codeexamples-android#1]
Sadly, Eclipse is deprecated.
Please let us import the projects via Android-Studio more easily. Currently it has a lot of issues with the repo...

**Comment by vogella** [comment]
Pull requests are welcome

**Comment by AndroidDeveloperLB** [comment]
I don't understand. What's wrong with what I wrote?
At least, for the new samples, that supports Lollipop, can they be converted?

**Comment by vogella** [comment]
See my comment, I'm happy to accept Pull requests from you

**Comment by AndroidDeveloperLB** [comment]
Sadly I never did this. 
But I've found 2 issues on the project of the jobScheduler:
- "onStartJob" returns true for you, which means it needs to perform background operations, yet it doesn't do anything (so it should return false). Not sure though what this causes the framework to do.
-You forgot to add this to the service in the manifest, otherwise it will crash:
        <service android:name=".TestJobService" android:permission="android.permission.BIND_JOB_SERVICE"
                 android:exported="true">
        </service>
