### ISSUE TITLE
android.support.v13.app.FragmentStatePagerAdapter  is deprecated

### ISSUE THREAD

**Issue by Mayank-Bhatnagar** [vogellacompany/codeexamples-android#10]
According to https://developer.android.com/reference/android/support/v13/app/FragmentStatePagerAdapter, android.support.v13.app.FragmentStatePagerAdapter isdeprecated.

Would you like to replace it with android.support.v4.app.FragmentStatePagerAdapter? I'll create merge request which for this fix.

**Comment by vogella** [comment]
Yes, please send PR

**Comment by Mayank-Bhatnagar** [comment]
I have created a merge request for this.

**Comment by Mayank-Bhatnagar** [comment]
This issue has been fixed now.
