### ISSUE TITLE
DaggerDiComponent class in dagger2simple Project

### ISSUE THREAD

**Issue by ezzieyguywuf** [vogellacompany/codeexamples-android#8]
I am going through your [Dagger 2 article](http://www.vogella.com/tutorials/Dagger/article.html). I have noticed that in the article, as well as in [MainActivity.java on your github repo](https://github.com/vogellacompany/codeexamples-android/blob/master/com.vogella.android.dagger2simple/app/src/main/java/com/vogella/android/dagger2simple/MyApplication.java) a `com.vogella.android.dagger2simple.components.DaggerDiComponent` is referenced.

Despite this, there is no mention in the article nor evidence in the github repo of a `DaggerDiComponent.java` file in the `src/main/java/com.vogella.android.dagger2simple/components` directory.

Is this class supposed to be generated by by dagger?

**Comment by vogella** [comment]
> Is this class supposed to be generated by by dagger?
Yes. Try a clean build to see it.

**Comment by ezzieyguywuf** [comment]
The problem was I was using Dagger v2.9. Apparently the "android-apt" functionality was moved to the gradle android plugin, so I had to do some adjustments to my gradle.build in order to use dagger v2.9.

**Comment by vogella** [comment]
> Is this class supposed to be generated by by dagger?
Yes. Try a clean build to see it.

**Comment by vogella** [comment]
Thanks for the info.

@daweiser please update the example to Dagger v2.9 and also adjust the tutorial.

**Comment by daweiser** [comment]
This can be closed. Please reopen, if you have additional remarks.
