### ISSUE TITLE
NPE in RxJavaSimpleActivity.java

### ISSUE THREAD

**Issue by jimandreas** [vogellacompany/codeexamples-android#9]
Thanks very much for putting together these examples!!
Found a minor NPE in RxJavaSimpleActivity.java:

The variable <pre><code> CompositeDisposable disposable;</pre></code> is not initialized before the line:

    disposable.add(subscribe);

and so it dies with NPE.   Just need to change to:

    CompositeDisposable disposable = new CompositeDisposable();

Full file path:

https://github.com/vogellacompany/codeexamples-android/blob/master/com.vogella.android.rxjava.simple/app/src/main/java/com/vogella/android/rxjava/simple/RxJavaSimpleActivity.java

**Comment by vogella** [comment]
Thanks. Fixed.
